version: 2
jobs:
  build:
    working_directory: ~/project/src
    docker:
      - image: circleci/php:7.4-node-browsers

      - image: circleci/mysql:5.7-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: laravel
          MYSQL_DATABASE: laraveldb
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_PASSWORD: secret

    steps:
      - checkout:
          path: ~/project

      - add_ssh_keys:
          fingerprints:
            - "fa:48:32:52:60:b9:cb:1e:62:0e:b7:dd:c7:79:f0:de"

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo pdo_mysql bcmath

      - run: mv .env.example .env

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: php artisan key:generate

      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=mysql --force

      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build